development: &development
  adapter: postgresql
  database: runaway
  username: runaway
  password: runaway
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: test_database_name

production:
  <<: *development
  database: production_db_name